version: '2.2'
services: 
  database:
    image: mysql:5.7
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projetdatabase
    ports:
      - 3307:3306 
  spring-boot:
    image: espritadmin/my1st-deploy:5
    container_name: spring
    ports:
      - 8089:8089
    depends_on:
      - database
    restart: on-failure  

  angular:
    image: esprituser/angularproject:dev
    container_name: angular
    ports:
      - 4200:4200 
    depends_on:
      - spring-boot
